USE project;
DROP TABLE IF EXISTS JazdyTestowe
DROP TABLE IF EXISTS Samochody
DROP TABLE IF EXISTS Zamowienia
DROP TABLE IF EXISTS Nadwozia
DROP TABLE IF EXISTS Silniki
DROP TABLE IF EXISTS Paliwa
DROP TABLE IF EXISTS Klienci
DROP TABLE IF EXISTS Modele
DROP TABLE IF EXISTS Marki
DROP TABLE IF EXISTS Dealerzy